import type { Metadata } from "next";
import { main, header } from "./css/page.css";
import "./css/reset.css";
import "./css/globalTheme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <header className={header}>
          <h1>로고</h1>
          <nav>로그인</nav>
        </header>
        <main className={main}>{children}</main>
      </body>
    </html>
  );
}
